### ISSUE TITLE
Any planned support for latte 3?

### ISSUE THREAD

**Issue by dakorpar** [contributte/latte-parsedown-extra#21]

**Comment by f3l1x** [comment]
Not for me. Do you need it?

**Comment by dakorpar** [comment]
yup I'll check and prepare PR then maybe nothing except composer dependencies needs to be changed

**Comment by f3l1x** [comment]
Done https://github.com/contributte/latte-parsedown-extra/releases/tag/2.0.0

**Comment by dakorpar** [comment]
@f3l1x did you actually tried it?
erusev/parsedown-extra is not compatible with php 8+, I just switched to different markdown parser, erusev is giving deprecation notices...

**Comment by f3l1x** [comment]
I see green tests.

https://github.com/contributte/latte-parsedown-extra/blob/c52619b55f79ff2d64e482646692c1d7a2156d20/tests/Cases/ParsedownFilter.phpt
https://github.com/contributte/latte-parsedown-extra/actions/runs/7193982638/job/19593520111

Can you give me more details?

**Comment by dakorpar** [comment]
https://github.com/erusev/parsedown-extra/issues/179



https://github.com/erusev/parsedown-extra/issues/177
